# -*- coding: utf-8 -*-
"""Aula7-Python

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PONZzkU4tzGqAoaVZh98MYrvRP_4CVcx
"""

AULA 7

WHILE

contador = 1
while contador <= 5: #ENQUANTO O CONTADOR FOR <= A 5 ADICIONE +1
    print("Número:", contador)
    contador += 1

n = 1
while n <= 10: #ENQUANTO O N FOR <= A 10 ADICIONE +1
    print("HELLO:", n)
    n += 1

contador = 10
while contador > 0:
     print(contador)
     contador -= 1
     print("Contagem")

EXERCÍCIO SENHA:
senha_correta = "senha123"
tentativas = 3

while tentativas > 0:
  senha = input("Digite a senha:")
  if senha == senha_correta:
    print("Acesso concedido.")
    break #Sai do loop se a senha estiver correta
  else:
    tentativas -= 1
    print  (f"Senha incorreta. Tentativas restantes: {tentativas}")
if tentativas == 0 :
    print("Acesso bloqueado.")

NOME:
while
nome = 'Ana'

while nome == 'Ana':
      print(f'Olá {nome}')
      break
else:
      print(f'Olá {nome}')


## Exercícios:

**Exercício 1: Contagem regressiva simples**
Escreva um programa que exiba uma contagem regressiva de 10 a 1, e depois imprima "Fogo!".
contagem = 11
while contagem > 0:
    contagem-= 1
    print(contagem)
if contagem == 0:
    print('Fogo!')


**Exercício 2: Soma de números pares**

Peça ao usuário que insira um número inteiro positivo e, em seguida, calcule a soma de todos os números pares de 2 até o número inserido.

number=int(input('Digite um número inteiro positivo:\n'))
soma = 0
while soma < number:
  soma +=2
  print(soma)
if soma == number:
  print('O número digitado foi', number)

Resolução:

n = int(input('Digite um número inteiro positivo:\n'))
soma_pares = 0
c = 2

while c <= n:
   soma_pares += c
   c += 2
print(f'A soma dos números pares de {n} é {soma_pares}')

**Exercício 3: Tabuada de multiplicação**

Peça ao usuário para inserir um número inteiro e mostre a tabuada de multiplicação desse número de 1 a 10.
number=int(input('Digite um número inteiro para que seja gerado a sua tabuada:\n'))
c = 0
print('Tabuada do ',number)
while c <= 10:
  resultado = number * c
  print(f'{number}X{c}={resultado}')
  c += 1


**Exercício 4: Números ímpares reversos**

Exiba uma contagem regressiva de números ímpares de 99 a 1.

c = 99 #valor do contador
while c>=1:
  print(c)
  c -= 2 #calculo e seu valor

___________________________________________________________________________

RANDOM

import random
n = random.random()
print(n)

RANDOM VEZES 10

import random
n = random.random()*10
print(n)

RANDOM ONDE DETERMINAMOS INICIO E FIM (INTERVALO)

import random
n = random.randint(1,3)
print(n)


import random
print('''Jogo da adivinhação
Tente acertar o número da máquina
Escolha um número entre 1 e 10!
''')
numero_da_maquina = random.randint(1,10)
chances = 3

while chances > 0:
     chute = int(input('Digite seu chute: '))
     if chute == numero_da_maquina:
        print('Sensacional você acertou! O número que a maquina escolheu foi ',numero_da_maquina)
        break
     else:
        chances -=1
        print('Você errou,ainda tem :',chances, 'chances')
else:
   print('Suas chances acabaram!')


EXERCICIOS:
**1 - Crie um número aleatório de 10, 5**

import random
n = random.randint(5,10)
print(n)

**2 - Crie 3 números aleatórios**
import random
numbers = 3

while numbers > 0:
   n = random.random()
   print(n)
   numbers -=1

**3 - Crie um número aleatório entre 10 a 30 utilize o range()**
import random

n = random.randrange(10,30)
print(n)